### ISSUE TITLE
[BUG] nx-serverless: Property 'port' does not match the schema. '7777' should be a 'number'.

### ISSUE THREAD

**Issue by tstackhouse** [flowaccount/nx-plugins#115]
**Describe the bug**
When using serverless offline, if the port is not explicitly specified in `workspace.json` it will fallback to the default in `libs/nx-serverless/src/builders/offline/schema.json` which is `"7777"`, not `7777`, which causes the above schema failure.

**To Reproduce**

1. In any project using nx-serverless, do not specify `port` in the options for the `serve` command in `workspace.json`
2. Attempt to run `nx serve`
3. Command fails with schema error 

**Expected behavior**
Serverless offline is started on the default port of 7777.

**Screenshots**
N/A

**Check which provider is affected:**
[x] AWS
[?] Azure
[?] Google Cloud Platform

**Check which framework is affected:**
[] Angular
[] Nodejs
[x] Serverless
[] Lambda
[] Infrastructure as a code

**Additional context**
I have a fix for this and am opening this issue for discussion before I open the PR.

**Comment by wickstargazer** [comment]
published with `1.1.1`
