### ISSUE TITLE
[BUG] When using npm as packager, pacakgelist is not properly computed resulting in "*" for all package versions

### ISSUE THREAD

**Issue by tstackhouse** [flowaccount/nx-plugins#116]
**Describe the bug**
When using npm as a packager, when attempting to prepare deployment packages, the dependency graph (i.e. `npm list`) is not properly output unless `npm install` is run first, resulting in multiple "unable to determine version" warnings and subsequently the generated deployments artifacts have "*" as the version tag for all their generated dependencies.  This can cause unexpected build or runtime failures as newer packages than are compatible can be inadvertently pulled in as part of the build process. (This occurred on my team when `got` released 12.0, which is pure ESM, while we are locked on ^11.0, which led me to investigate this issue)

**To Reproduce**

1. In a project configured with "NPM" as the "packager" option for `nx deploy`, with dependencies set, run `nx deploy`.
2. Observe Unable to determine version warnings in output
3. Examine package.json in deployment artifact(s) and observe "*" for all dependency versions

**Expected behavior**
The proper version is tagged in the generated package.json for the deployment artifact(s)

**Screenshots**
N/A

**Check which provider is affected:**
[x] AWS
[?] Azure
[?] Google Cloud Platform

**Check which framework is affected:**
[] Angular
[] Nodejs
[x] Serverless
[] Lambda
[] Infrastructure as a code

**Additional context**
I have a fix for this and am opening this issue for discussion before I open the PR.

**Comment by tstackhouse** [comment]
One point of note, this only occurs on a clean build.  Subsequent builds with an existing `dist` folder will work correctly.

**Comment by wickstargazer** [comment]
published with `1.1.1`
