### ISSUE TITLE
[FEAT] Webpack stats.json support

### ISSUE THREAD

**Issue by tstackhouse** [flowaccount/nx-plugins#118]
**Is your feature request related to a problem? Please describe.**
It doesn't seem like we support the `--statsJson` option, setting that to true does not produce a stats.json file in `dist/apps/<app>` the same way that an app using e.g. the angualr devkit builder does.

**Describe the solution you'd like**
In `build.impl.ts` in the callback for the webpack process, we have access to the `stats` object, and can to `stats.toJson("verbose")` to get the data that a tool like `webpack-bundle-analyzer` can process.

**Describe alternatives you've considered**
I'm not sure there's any other good way to evaluate how the build process works and find ways to optimize.  I know my use case is a bit unique, we have 70+ lambdas in one app and it results in relatively long builds, and I've actually had to use some custom forks of this library and serverless in order for it to work properly, and have been trying to remedy that now that I have time.

**Check which provider is affected:**
[] AWS
[] Azure
[] Google Cloud Platform

**Check which framework is affected:**
[] Angular
[] Nodejs
[x] Serverless
[] Lambda
[] Infrastructure as a code

**Additional context**
I'm planning on putting together a PR for this shortly, since it's relatively minor.

**Comment by wickstargazer** [comment]
hey we will merge and publish it by the week

**Comment by tstackhouse** [comment]
If you’re good with that PR, it would be awesome if we can get it in, we’ve been trying to get our project into the latest plug-in and serverless 2, but it’s a hefty app and was running into memory issues

**Comment by wickstargazer** [comment]
merged and published to `1.1.2`

**Comment by tstackhouse** [comment]
Oh I see you were referring to #120, yes, that was definitely something to be merged, as it was a bugfix for this PR.

I was referring to #121.  I was on mobile so a long reply is hard to manage.
