### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by deviant32** [flowaccount/nx-plugins#19]
How do I pass in a stage when trying to deploy?  I am running `nx deploy sls-cognito-triggers --stage=staging` but every time it deploys, it deploys to dev.

**Comment by wickstargazer** [comment]
Hi you can use ‘env.json’ and add ‘stage’ property to it

Or you can also add ‘stage’ property to the ‘angular.json’ configuration section of deploy

**Comment by wickstargazer** [comment]
@deviant32  I have added the sample config in the `Readme` for nx-serverless as well. Hope it clarifies things for future users! I will close this now! 👍
