### ISSUE TITLE
[BUG] Can't include a yml function file.

### ISSUE THREAD

**Issue by hiepinnomizetech** [flowaccount/nx-plugins#23]
**Describe the bug**
Can't include a yml function file.

**To Reproduce**
I move below code to hello-world.yml
`  
hello-world:

    handler: src/functions/hello-world/hello-world.handler

    events:

      - http:

          path: hello-world

          method: get
`
And update serverless.yml
hello-world: '${file(/src/functions/hello-world/hello-world.yml)}'

**Expected behavior**
serverless.yml will include code of hello-world.yml

**Check which provider is affected:**
[x] AWS
[] Azure
[] Google Cloud Platform

**Check which framework is affected:**
[] Angular
[] Nodejs
[x] Serverless
[] Lambda
[] Infrastructure as a code

**Comment by wickstargazer** [comment]
Could you help paste a reference to serverless importing yml as function? I dont think i considered this feature when building it as we don't use it. But I would be happy to in-corporate it into the library! 😄

**Comment by hiepinnomizetech** [comment]
I have created an example at https://github.com/hiepinnomizetech/nx-serverless
In this example, I separate AWS cloud formation to 3 files serverless.config.yml, hello-world.yml and serverless.yml. But I think file() function isn't supported by this plugin (https://www.serverless.com/framework/docs/providers/aws/guide/variables#reference-variables-in-other-files).

I hope you can include this feature in the plugin. My current project has a large serverless.yml. If this plugin can separate serverless.yml, it is so great.
Thank you very much!

**Comment by wickstargazer** [comment]
Hi! ... was wonderng is there an error message somewhere? because i check the serverless code, and it seems to be included, but i am having a hunch about the file path that might be screwing up ...

Below is their function ... If you can provide an error or any warning messages? If not I will debug into their code. If you could help out it would be awesome .. 😄 

`D:\<your-project>\node_modules\serverless\lib\classes\Variables.js`
```javascript
getValueFromFile(variableString) {
    const matchedFileRefString = variableString.match(this.fileRefSyntax)[0];
    const referencedFileRelativePath = matchedFileRefString
      .replace(this.fileRefSyntax, (match, varName) => varName.trim())
      .replace('~', os.homedir());

    let referencedFileFullPath = path.isAbsolute(referencedFileRelativePath)
      ? referencedFileRelativePath
      : path.join(this.serverless.config.servicePath, referencedFileRelativePath);

    // Get real path to handle potential symlinks (but don't fatal error)
    referencedFileFullPath = fse.existsSync(referencedFileFullPath)
      ? fse.realpathSync(referencedFileFullPath)
      : referencedFileFullPath;

    let fileExtension = referencedFileRelativePath.split('.');
    fileExtension = fileExtension[fileExtension.length - 1];
    // Validate file exists
    if (!this.serverless.utils.fileExistsSync(referencedFileFullPath)) {
      return BbPromise.resolve(undefined);
    }

    let valueToPopulate;

    // Process JS files
    if (fileExtension === 'js') {
      // eslint-disable-next-line global-require, import/no-dynamic-require
      const jsFile = require(referencedFileFullPath);
      const variableArray = variableString.split(':');
      let returnValue;
      if (variableArray[1]) {
        let jsModule = variableArray[1];
        jsModule = jsModule.split('.')[0];
        returnValue = jsFile[jsModule];
      } else {
        returnValue = jsFile;
      }

      if (typeof returnValue === 'function') {
        valueToPopulate = returnValue.call(jsFile, this.serverless);
      } else {
        valueToPopulate = returnValue;
      }

      return BbPromise.resolve(valueToPopulate).then(valueToPopulateResolved => {
        let deepProperties = variableString.replace(matchedFileRefString, '');
        deepProperties = deepProperties.slice(1).split('.');
        deepProperties.splice(0, 1);
        return this.getDeeperValue(deepProperties, valueToPopulateResolved).then(
          deepValueToPopulateResolved => {
            if (unsupportedJsTypes.has(typeof deepValueToPopulateResolved)) {
              const errorMessage = [
                'Invalid variable syntax when referencing',
                ` file "${referencedFileRelativePath}".`,
                ' Check if your javascript is returning the correct data.',
              ].join('');
              return BbPromise.reject(new this.serverless.classes.Error(errorMessage));
            }
            return BbPromise.resolve(deepValueToPopulateResolved);
          }
        );
      });
    }

    // Process everything except JS
    if (fileExtension !== 'js') {
      valueToPopulate = this.serverless.utils.readFileSync(referencedFileFullPath);
      if (matchedFileRefString !== variableString) {
        let deepProperties = variableString.replace(matchedFileRefString, '');
        if (deepProperties.substring(0, 1) !== ':') {
          const errorMessage = [
            'Invalid variable syntax when referencing',
            ` file "${referencedFileRelativePath}" sub properties`,
            ' Please use ":" to reference sub properties.',
          ].join('');
          return BbPromise.reject(new this.serverless.classes.Error(errorMessage));
        }
        deepProperties = deepProperties.slice(1).split('.');
        return this.getDeeperValue(deepProperties, valueToPopulate);
      }
    }
    return BbPromise.resolve(valueToPopulate);
  }
```

**Comment by wickstargazer** [comment]
Hi @hiepinnomizetech I haven't forgot this, will be looking into it this working week 😄

**Comment by hiepinnomizetech** [comment]
@wickstargazer , i have checked and I see serverless has included other files by using file() function. Thank so much!

**Comment by wickstargazer** [comment]
@hiepinnomizetech so, did you have to add some new package to the `package.json`? If so lets fix it to be a depedency needed for the lib :)

**Comment by wickstargazer** [comment]
@hiepinnomizetech So should i add some new dependency for the `file()` funciton? i still dint get the answer 😄

**Comment by hiepinnomizetech** [comment]
@wickstargazer thanks! 
I only tested file() function can load another file data, but I didn't test why it doesn't work in Demo project (I think it is caused by include URL).

**Comment by hiepinnomizetech** [comment]
@wickstargazer , I have found root cause.
If I use file() function on Lambda function section:
`
functions:
  hello-world: ${file(hello-world.yml)}
`
hello-world.yml will not be loaded because file() function doesn't run.
But if i use file() function on custom section:
`
custom:
  config: ${file(serverless.config.yml)}
`
serverless.config.yml will be loaded.

![image01](https://user-images.githubusercontent.com/57709483/87028393-c347a200-c208-11ea-9149-95c630d98074.png)

**Comment by wickstargazer** [comment]
Ah ok, yes we can fix that by moving the sequence around a bit

**Comment by nhammond101** [comment]
Any update @wickstargazer?

Our project's growing to a size where splitting into separate files would be useful

**Comment by wickstargazer** [comment]
i am looking at the project this week and next. We will have an update within first week jan and again first week feb 👍🏽

**Comment by wickstargazer** [comment]
following this issue for the fix --> https://github.com/serverless/serverless/issues/2997
