### ISSUE TITLE
[FEAT] Ability to pass in the path of tsconfig.json for scully-plugin-angular-delay

### ISSUE THREAD

**Issue by codephobia** [flowaccount/nx-plugins#24]
**Is your feature request related to a problem? Please describe.**
Currently when using scully-plugin-angular-delay with an app that is in a yarn monorepo, the tsconfig.json lives outside of the package folder (scully root path). This throws an error as we do not have any way to pass in the correct path of the file.

**Describe the solution you'd like**
Ability to pass in the path for the tsconfig.json file.

**Describe alternatives you've considered**
Looking at the source code, this seems like it would be the best solution.

**Check which provider is affected:**
[] AWS
[] Azure
[] Google Cloud Platform

**Check which framework is affected:**
[x] Angular
[] Nodejs
[] Serverless
[] Lambda
[] Infrastructure as a code

**Additional context**
I'd be willing to put together a PR for this, but this could be a pretty big breaking change.

**Comment by wickstargazer** [comment]
That would be a nice touch...would you like to do a PR? I can walk you through it :)

If not i will get to it in a week time

**Comment by etavener** [comment]
Hi, great to see this recently merged, I have a similar problem I would like to resolve with this fix. Please can you release this new feature.

**Comment by wickstargazer** [comment]
Hi!, I have published version `0.0.8` please try it out and if it works out let me know! Thankz a ton for the PR! ... @codephobia

**Comment by wickstargazer** [comment]
ok, will close this until there is some more updates
