### ISSUE TITLE
[BUG] - Update readme.md to be correct

### ISSUE THREAD

**Issue by etavener** [flowaccount/nx-plugins#27]
**Describe the bug**
In the Readme the command to NPM install should be updated to:
`npm install @flowaccount/scully-plugin-angular-delay --save-dev`

**Check which provider is affected:**

**Check which framework is affected:**
[X] Angular
[] Nodejs
[] Serverless
[] Lambda
[] Infrastructure as a code

**Additional context**

**Comment by wickstargazer** [comment]
I have updated the readme and published `0.0.8`
