### ISSUE TITLE
[BUG] scully-plugin-angular-delay

### ISSUE THREAD

**Issue by etavener** [flowaccount/nx-plugins#34]
**Describe the bug**
When I add your plugin to my static site there seems to be a bug.

I get the following console error:
`Uncaught TypeError: scriptsToLoad.forEach is not a function`

The scripts are not loaded at all.

On further investigation, when I look at the code added to my HTML page I see this:

```javascript
window.addEventListener('load', function(event) {
        setTimeout( function() {
          scriptsToLoad.forEach(entry => {
            appendScript(entry);
          });
        }, 1500);
      });
    scriptsToLoad = '["runtime-es5.js","polyfills-es5.js","polyfills-es2015.js","vendor-es5.js","runtime-es2015.js","vendor-es2015.js","main-es2015.js","main-es5.js","styles-es2015.js","styles-es5.js"]'
```
So I can see the issue is a `forEach` on a string when an array is expected.

I think this can be easily fixed by having this line instead (I removed the single quotes wrapping the `${}`:
```javascript
appendScript += `scriptsToLoad = ${JSON.stringify(sorted)}`;
```

I've also made this change in this PR:
https://github.com/flowaccount/nx-plugins/pull/33

If this is incorrect, please let me know what the solution is.

**Versions**
@flowaccount/scully-plugin-angular-delay@0.0.8
@scullyio/scully@0.0.99
@scullyio/ng-lib@0.0.27
@scullyio/init@0.0.28

**Check which provider is affected:**
[] AWS
[] Azure
[] Google Cloud Platform

**Check which framework is affected:**
[x] Angular
[] Nodejs
[] Serverless
[] Lambda
[] Infrastructure as a code

**Comment by etavener** [comment]
If you are happy with this change, then please merge and release a new version.

**Comment by wickstargazer** [comment]
Hi! ... i can review it and check it out. At the moment i haven't add some plugins into the commitizen config, hence the build is failing... I will do that as well :)

**Comment by etavener** [comment]
Created new PR with requested updated changes.
