### ISSUE TITLE
[BUG] Angular Delay plugin - when target is `es5`

### ISSUE THREAD

**Issue by etavener** [flowaccount/nx-plugins#40]
**Describe the bug**
I've come across some issues with a project using this plugin.

The project has a `tsconfig.json` with a `target` that is `es5`.

It only added 1 script to the scripts to load (polyfills as this was the only one with es5 in the name).

I updated the target inside `tsconfig.json` from `es5` to `es2015` and now it works.

**Check which provider is affected:**
[] AWS
[] Azure
[] Google Cloud Platform

**Check which framework is affected:**
[x] Angular
[] Nodejs
[] Serverless
[] Lambda
[] Infrastructure as a code

**Additional context**

**Comment by wickstargazer** [comment]
Yes, i was having the issue with `polyfills` as well. It will add everything that is in `stats.json` if it does not exists in `stats.json` it will have to be manually added. Or is there a more deeper reason I wouldn't know

**Comment by wickstargazer** [comment]
Hi i thinking you have solved the issue on your end so i will close this for now 😄
