### ISSUE TITLE
[BUG] Angular Delay Plugin - Do you have this working at all? Please share the tsconfig.json

### ISSUE THREAD

**Issue by etavener** [flowaccount/nx-plugins#41]
**Describe the bug**
Hi, I seem to be finding a lot of issues with this library and I'm wondering if it has ever worked.

My angular scripts now load after the delay but no code is executed. For example, I put a console log on a component and it never happens. I also have a form that doesn't work. No Angular code is executed after you load the scripts.

I was wondering if you have this working, please can you share how you use it. I may have changed something in my tsconfig to create this issue, although it works without this plugin.

**Check which provider is affected:**
[] AWS
[] Azure
[] Google Cloud Platform

**Check which framework is affected:**
[x] Angular
[] Nodejs
[] Serverless
[] Lambda
[] Infrastructure as a code

**Additional context**

**Comment by wickstargazer** [comment]
Hi we have this working on production --> https://flowaccount.com/

Here is the `tsconfig.json`
```json
{
  "extends": "./tsconfig.json",
  "compileOnSave": false,
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "typeRoots": ["node_modules/@types"],
    "lib": ["es2017", "dom", "esnext.asynciterable"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "resolveJsonModule": true,
    "baseUrl": ".",
    "outDir": "../../../dist/out-tsc",
    "types": []
  },
  "files": [
    "src/main.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "**/*.ts",
    "src/environments/environment.ts"
  ],
  "exclude": [
    "src/test-setup.ts",
    "**/*.spec.ts",
    "server.ts",
    "handler.ts",
    "src/environments/*",
    "scully.config.ts",
    "scully-mobile.config.ts"
  ]
}
```

Let me know if you need further assistance, I will be happy to help you out. Or we can remove the tsconfig totally as you suggested? Although I have to test that out first

**Comment by wickstargazer** [comment]
@etavener did you get it to work?

**Comment by wickstargazer** [comment]
Hi i thinking you have solved the issue on your end so i will close this for now 😄
