### ISSUE TITLE
[BUG] Incorrect AWS region value but default value is source-map-support/register

### ISSUE THREAD

**Issue by phong-innomizetech** [flowaccount/nx-plugins#46]
I tried to use the serverless offline to run the application on local and invoke some AWS Services but It's always got timeout because of the serverless always got region is **source-map-support/register**.

**Check which provider is affected:**
[x] AWS

**Check which framework is affected:**
[x] Nodejs
[x] Serverless

**Additional context**
I am not sure why we need provide the default the argument in offline.impl  as:
const args = ['-r', 'source-map-support/register'];

Please not that serverless also use option "-r" to provide the region on application refer to https://www.serverless.com/framework/docs/providers/aws/cli-reference/deploy/ 
`--region or -r The region in that stage that you want to deploy to.`

**Comment by wickstargazer** [comment]
i think we can removed it, it must be a mistake when i was implementing the builder, thanks for spotting it out

**Comment by tstackhouse** [comment]
I have a pending PR to fix this very issue.

**Comment by wickstargazer** [comment]
I have published version `0.5.2` for this fix :) ... hope it solve the issue and can let me know if it does not Thankz for the PR!
