### ISSUE TITLE
[BUG] package.custom not supported in serverless.yml

### ISSUE THREAD

**Issue by tstackhouse** [flowaccount/nx-plugins#49]
**Describe the bug**
In the default serverless.yml generated by nx-serverless, it includes the `custom` key under the `package` property.  In recent versions of serverless, this fails schema validation, as seen in the following output:

```
Serverless: Configuration warning at 'package': unrecognized property 'custom'
Serverless:  
Serverless: If you prefer to not continue ensure "configValidationMode: error" in your config
Serverless: If errors are influenced by an external plugin, enquiry at plugin repository so schema extensions are added (https://www.serverless.com/framework/docs/providers/aws/guide/plugins#extending-validation-schema)
Serverless: If errors seem invalid, please report at https://github.com/serverless/serverless/issues/new?template=bug_report.md
Serverless: If you find this functionality problematic, you may turn it off with "configValidationMode: off" setting
```

**To Reproduce**
Generate an nx-serverless project using a recent release of serverless (I have observed this in 1.79.0, but this likely also includes other versions  > 1.58.0, I don't have the time to bisect my way to the first version, but I wanted to log the issue)

Run serverless and observe the validation warning.

**Expected behavior**
No warning is thrown by serverless

**Screenshots**

**Check which provider is affected:**
[] AWS
[] Azure
[] Google Cloud Platform

**Check which framework is affected:**
[] Angular
[] Nodejs
[x] Serverless
[] Lambda
[] Infrastructure as a code

**Additional context**
The generated configuration can be seen originating in these files:
https://github.com/flowaccount/nx-plugins/search?q=enable_optimize&unscoped_q=enable_optimize

**Comment by wickstargazer** [comment]
Ok that can be removed pretty quickly .. but a question, should we have a backward compatable for serverless version? We are using version older than 1.7 and it does not seems to fail validation or spit out a warning. Or i haven't looked at it enough. I will check it out while running some test.

Thankz!

**Comment by tstackhouse** [comment]
It doesn't seem to be a distinct failure, just a warning, which may mean that the configuration is simply being quietly ignored.  I had dome some searching on that `enable_optimize` flag, and didn't really come up with much documentation outside of a single blog article.

**Comment by wickstargazer** [comment]
removing this in v0.5.3
