### ISSUE TITLE
[BUG] npx nx deploy fails

### ISSUE THREAD

**Issue by stefan-karlsson** [flowaccount/nx-plugins#50]
**Describe the bug**
The command `npx nx deploy` fails.

I dont have yarn installed on my computer, what do i need to do to use npm?

"@flowaccount/nx-serverless": "^0.5.2",

**Expected behavior**
Want to be able to deploy my web application

**Screenshots**
![image](https://user-images.githubusercontent.com/25538602/90988432-01b7d700-e593-11ea-92d6-85f4d79415b0.png)

**Check which provider is affected:**
[X] AWS
[] Azure
[] Google Cloud Platform

**Check which framework is affected:**
[] Angular
[] Nodejs
[X] Serverless
[] Lambda
[] Infrastructure as a code

**Additional context**
Using windows 10 and npm as a package manager

**Comment by wickstargazer** [comment]
Ok! I will take a look at it asap. Also I am looking for some contributors, let me know if you are interested 😄  Since I have been focusing my time into building some company infrastructure, i am a bit off an on but will be improving it since we are mainly serverless atm !

**Comment by stefan-karlsson** [comment]
> Also I am looking for some contributors, let me know if you are interested

I am happy to help out, but i am in the same situation as you. The work takes alot of my time :)

**Comment by stefan-karlsson** [comment]
I did a quick look but having some issues installing the solution on Windows as you mentioned in the documentation.

When i [check this code](https://github.com/flowaccount/nx-plugins/blob/master/libs/nx-serverless/src/utils/packagers/index.ts#L75-L84) it looks like the `packager('yarn')` function only checks if the yarn package manager [has a implementation](https://github.com/flowaccount/nx-plugins/blob/master/libs/nx-serverless/src/utils/packagers/index.ts#L49-L55). Since it has a implementation we will use that. 
```
  let packagerInstance = null;
  if (packager('yarn')) {
    packagerInstance = Yarn;
  } else if (packager('npm')) {
    packagerInstance = NPM;
  } else {
    return of({
      success: false,
      error: 'No Packager to process package.json, please install npm or yarn'
    });
  }
```

I guess what we instead wants to do here is:
1. Check if there is a package-lock.json file in the project (NPM)
2. As a fallback try to execute the commands npm and yarn

There is a package for this that i havn't tried out:
https://github.com/egoist/detect-package-manager
