### ISSUE TITLE
[BUG?] Possible problems with plugins that use require() 

### ISSUE THREAD

**Issue by azgorov** [flowaccount/nx-plugins#54]
**Describe the bug**
I am trying to use nx-serverless with serverless-stack-output plugin and it always fails if I set handler function

**To Reproduce**

1. Add serverless-stack-output plugin in serverless.yml. It does not matter if it is original package or one of latets forks like @anttiviljami/serverless-stack-output
2. Add custom typescript or javascript handler function. 
3. Add custom>output>handler path to function
4. Run nx deploy app
4. See error : Cannot process Stack Output: Cannot find module "path to module"

If sls deploy command is executed from dist folder everything is fine. Maybe problem is related to setting servicePath or problem is in serverless cli.

**Expected behavior**
 The same result as executing sls deploy

**Screenshots**
-

**Check which provider is affected:**
[X] AWS
[] Azure
[] Google Cloud Platform

**Check which framework is affected:**
[] Angular
[] Nodejs
[X] Serverless
[] Lambda
[] Infrastructure as a code

**Additional context**
-

**Comment by wickstargazer** [comment]
Is this
1. Because you want to generate only one function at a time? By specifying it in the yaml 

Or

2. Just because you added the stack-output plugin

So i know where to look

**Comment by azgorov** [comment]
Hello @wickstargazer ,

If you add stack-output plugin and include handler function it fails. It does not matter what other stuff is included in yml.

Kalin

**Comment by wickstargazer** [comment]
Hello @azgorov this issue will be focus in releasing version 1.0 ... I am reshuflling the way servicePath works.

**Comment by wickstargazer** [comment]
fixed in v0.5.3 pending test
