### ISSUE TITLE
[BUG]Stage option passed to SLS build doesn't make it to serverless.yml config.

### ISSUE THREAD

**Issue by warrendugan** [flowaccount/nx-plugins#57]
**Describe the bug**
When I run `nx run <project>:sls --configuration deploy-production` the `STAGE` key still has a value of `dev`

**To Reproduce**
https://github.com/warrendugan/nx-sls

**Expected behavior**
When using deploy-production vs. deploy-dev, I expect the stage option to be passed to the serverless configuration so it deploys to the correct environemnt. Currently I get the same outcome (see screenshot) regardless of which command is used. 

**Screenshots**
![image](https://user-images.githubusercontent.com/23459839/96895114-e78a6000-1440-11eb-98f8-8657b5565324.png)

**Check which provider is affected:**
[x] AWS

**Check which framework is affected:**
[x] Angular
[x] Nodejs
[x] Serverless
[x] Lambda

**Comment by PeterWunderlich** [comment]
Experiencing the same issue and tried to find the reason for that one. No luck until now. 😅

**Comment by wickstargazer** [comment]
change to pass argument through `workspace.json` or `angular.json` instead
