### ISSUE TITLE
[BUG] nx add throws error `Could not find project "@flowaccount/nx-serverless"`

### ISSUE THREAD

**Issue by bmcilw1** [flowaccount/nx-plugins#65]
**Describe the bug**

nx add throws could not find project error

**To Reproduce**

```bash
mkdir nx-sls
cd nx-sls
npx create-nx-workspace test --preset=empty --nx-cloud=false # Same with create-nx-workspace@latest
cd test
nx add @flowaccount/nx-serverless
```

Returns error `Could not find project "@flowaccount/nx-serverless"`

**Expected behavior**

The given instructions for installing the plugin should not produce an error

**Check which provider is affected:**
[x] AWS
[x] Azure
[x] Google Cloud Platform

**Check which framework is affected:**
[x] Angular
[x] Nodejs
[x] Serverless
[x] Lambda
[x] Infrastructure as a code

Affects everything - can't add to a project

```text
nx --version
11.1.5
```

**Comment by bmcilw1** [comment]
@wickstargazer I'd very much appreciate it if you could let me know what I can do to help with this bug. I've tried every approach I can find on the internet for getting our nx monorepo hosted in AWS lambda using the serverless sdk, but had very little luck. I'd be happy to try to create a PR with changes, if only I have at least some idea what to change.

Thanks!

**Comment by bmcilw1** [comment]
For those who find this later, you must have the angular stuff installed to use this plugin.

This setup resolves the nx add error (notice the preset os angular)

```bash
mkdir test-nx-sls
cd test-nx-sls
npx create-nx-workspace test --preset=angular --nx-cloud=false --linter=eslint --style=css --appName=testapp
cd test
nx add @flowaccount/nx-serverless
```

**Comment by wickstargazer** [comment]
Hi i am trying to remove the preset-angular so lets open this back up

**Comment by wickstargazer** [comment]
hi @bmcilw1 sice the refactor, there is no angular add schematics anymore. So the solution is to do `yarn add @flowaccount/nx-serverless` 

lets close this?
