### ISSUE TITLE
[BUG] Missing compat.ts for sls executor

### ISSUE THREAD

**Issue by milocosmopolitan** [flowaccount/nx-plugins#94]
**Describe the bug**
Because this is missing, command can't be invoked.

**To Reproduce**
run sls command after inserting the target on workspace.json manually.

**Expected behavior**
to be able to run sls commands

**Check which provider is affected:**
[x] AWS
[] Azure
[] Google Cloud Platform

**Check which framework is affected:**
[] Angular
[] Nodejs
[x] Serverless
[] Lambda
[] Infrastructure as a code

**Comment by dylanschoenmakers** [comment]
When will this be released? Currently impacted by this bug :)

**Comment by wickstargazer** [comment]
just released `1.0.0-beta.7` apologies, was stuck trying to fix deploy per function.
